### ISSUE TITLE
[BUG] Build is not working

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [splunk/security_content#2948]
### **Describe the bug**
As per documentation, there should be possible to build package after generation of that package. 
but it is not. 

it is said that need to install `slim`, so i've added `splunk-packaging-toolkit` to requrements.txt and installed as other reuqurements. 
but slim is failing.

### **Expected behavior**
it works as described in documentation. If there are some old dependencies in python2, so documentation should be updated. 

### **Screenshots**
```
Traceback (most recent call last):
  File "/usr/local/bin/slim", line 5, in <module>
    from slim.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/slim/__init__.py", line 10, in <module>
    from . describe import describe
  File "/usr/local/lib/python3.10/dist-packages/slim/describe.py", line 9, in <module>
    from slim.app import AppDependencyGraph, AppSource
  File "/usr/local/lib/python3.10/dist-packages/slim/app/__init__.py", line 8, in <module>
    from . _configuration import (
  File "/usr/local/lib/python3.10/dist-packages/slim/app/_configuration.py", line 11, in <module>
    from . _configuration_validator import AppConfigurationValidator
  File "/usr/local/lib/python3.10/dist-packages/slim/app/_configuration_validator.py", line 13, in <module>
    from . _configuration_spec import AppConfigurationPlacement, AppConfigurationSpec
  File "/usr/local/lib/python3.10/dist-packages/slim/app/_configuration_spec.py", line 55, in <module>
    from . _configuration_validation_plugin import AppConfigurationValidationPlugin
  File "/usr/local/lib/python3.10/dist-packages/slim/app/_configuration_validation_plugin.py", line 12, in <module>
    from .. utils import SlimLogger, encode_filename, encode_series, slim_configuration
  File "/usr/local/lib/python3.10/dist-packages/slim/utils/__init__.py", line 18, in <module>
    from . ignore import *
  File "/usr/local/lib/python3.10/dist-packages/slim/utils/ignore.py", line 9, in <module>
    from collections import Iterable, OrderedDict  # pylint: disable=no-name-in-module
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

### **App Version:**
 latest package 4.21

**Comment by yaroslav-nakonechnikov** [comment]
as i may understand, this is due to python 3.10. 
and it is strange, why venv using 3.10, or what is wrong? 

```
(venv) user@star:~/security_content-4.21.0$ which python
/home/user/security_content-4.21.0/venv/bin/python
(venv) user@star:~/security_content-4.21.0$ python --version
Python 3.10.12
(venv) user@star:~/security_content-4.21.0$ /home/user/security_content-4.21.0/venv/bin/python --version
Python 3.10.12
```

**Comment by yaroslav-nakonechnikov** [comment]
so, i had to update some ~20 py files with `Import from collections` and changed it to `Import from collections.abc` and it started to work.  

but this is not expected way to solve it.

**Comment by josehelps** [comment]
Hey @yaroslav-nakonechnikov I believe you might be using an old version of our tooling, we migrated all these tools over to https://github.com/splunk/contentctl .. give those a try, I will work on updating our README here so it won't mislead other users. Thank you for raising!

**Comment by yaroslav-nakonechnikov** [comment]
@josehelps but according to releases and timestamps for it - there is a feel, that security_content is more active project.

**Comment by josehelps** [comment]
it is definetly a more active project since we publish our active detection development there, but the tooling for it now lives on contentctl.

**Comment by yaroslav-nakonechnikov** [comment]
thanks!
